version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - "docker.env"
    depends_on:
      - "postgres"
  postgres:
      image: postgres:13
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
      ports:
          - '5438:5432'
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables; gets run on startup and is idempotent
          - ./data/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
